import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Menu,MapPin,Phone,Instagram,ChevronDown,X,CalendarDays,Gift,Flower2}from'lucide-react';import'./styles.css';

const menuGroups=[{title:'Matcha',items:['White Chocolate Matcha','Raspberry & White Chocolate Matcha','Raspberry & White Chocolate Matcha','Mango Matcha','Vanilla Collagen Matcha']},{title:'Iced Coffee',items:['Iced Pistachio White Chocolate Latte','Iced Spanish Latte']},{title:'Juices & Soft Drinks',items:['Orange Juice','Cola','Still Water']},{title:'Hot Drinks',items:['Classic Hot','Strawberry & Lime','Pomegranate & Red Bull Fusion']},{title:'Hot Drinks (FIA)',items:['Psh Chai','Pistachio Chai','Lotus Hot Chocolate','Hazelnut Hot Chocolate','Vanilla Latte','Rosehip Latte','Cappuccino','Americano','Flat White','Cappuccino','Latte','Mocha','English Tea','Green Tea']},{title:'Add Ons',items:['Extra Espresso Shot','Oat Milk','Vanilla Caramel','Hazelnut Syrup','Extra Whip']},{title:'Bakery',items:['Cheesecake Choc Cookie','Pistachio & White Chocolate Cookie','Pistachio & Blackberry Cookie','Peach & Croissant','Raspberry Croissant']}];
const brunch=[{title:'Signature Pocket Toast',items:['Honey Roast Pocket','Spicy Chicken Samba','Avo & Chili','Arancello Veg Taco']},{title:'Pasta',items:['Creamy Garlic Prawn & Steak','Crispy Chicken Alfredo','Crispy Pesto Bacon Salad','Chicken Caesar Pasta Salad']},{title:'Baguettes',items:['Fried Chicken Baguette','Chicken Caesar Baguette','Nduja & Tomato Baguette']},{title:'Salads',items:['Nocino Salad','Chicken Caesar Salad']},{title:'Fries',items:['Truffle Skinny Fries','Harissa Chicken Fries']},{title:'French Toasts',items:['Brioche French Toast with Salted Honey','Mixed Berry French Toast','Kunafa Strawberry French Toast','Nutella French Toast']},{title:'On The Side',items:['Fries','Garlic Bread','Garlic Parmesan Fries']},{title:'Add Ons',items:['Scoop of Soft Serve']},{title:'Breakfast',items:['Steak & Egg Brioche','Three Cheese Miso Toast']},{title:'Saturday Evenings Only',items:['House Tiramisu']}];

function App(){const[open,setOpen]=useState(false);const[booking,setBooking]=useState(false);const[newsletter,setNewsletter]=useState('');const submitNewsletter=e=>{e.preventDefault();setNewsletter('Thanks — you’re on the FIA list.');};return <div className="app">
<header className="nav"><a className="logo" href="#home">FIA<span>COFFEEHOUSE</span></a><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav-links open':'nav-links'}>{['Home','Menu','Florals','Events','Gallery','About','Visit Us'].map(i=><a key={i} href={'#'+i.toLowerCase().replaceAll(' ','-')} onClick={()=>setOpen(false)}>{i}</a>)}<button className="primary" onClick={()=>setBooking(true)}>Book a Table</button></nav></header>
<section id="home" className="hero"><div className="hero-overlay"><p className="eyebrow">COFFEEHOUSE · BRUNCH · FLORALS</p><h1>Good Coffee.<br/>Brighter Days.</h1><p className="lead">Speciality coffee, seasonal brunch and beautiful florals — all under one roof in the heart of Preston.</p><div className="actions"><a className="light-btn" href="#menu">View Menu</a><button className="dark-outline" onClick={()=>setBooking(true)}>Book a Table</button></div></div></section>
<section className="intro"><p className="eyebrow">THE FIA EXPERIENCE</p><h2>A space for coffee, conversation and creativity.</h2><p>At FIA, speciality coffee meets fresh brunch and beautiful florals, creating a space where good food and great ideas bloom.</p><div className="pillars"><article><div className="pic coffee"></div><span>COFFEE</span><small>Speciality coffee, made with care</small><a href="#menu">Explore →</a></article><article><div className="pic brunch"></div><span>BRUNCH</span><small>Fresh flavours, all day</small><a href="#menu">Explore →</a></article><article><div className="pic floral"></div><span>FLORALS</span><small>Blooms for every moment</small><a href="#florals">Explore →</a></article></div></section>
<section id="menu" className="menu-section"><div className="section-head"><p className="eyebrow">OUR MENU</p><h2>Seasonal ingredients.<br/>Thoughtfully prepared.</h2></div><div className="menu-grid">{menuGroups.map(g=><article className="menu-card" key={g.title}><h3>{g.title}</h3>{g.items.map((it,i)=><div className="row" key={i}><span>{it}</span><span>›</span></div>)}</article>)}</div><div className="brunch-panel"><div className="brunch-title"><p className="eyebrow">FIA BRUNCH</p><h2>Brunch looks better together.</h2></div><div className="brunch-grid">{brunch.map(g=><article key={g.title}><h3>{g.title}</h3>{g.items.map((it,i)=><div className="row" key={i}><span>{it}</span><span>›</span></div>)}</article>)}</div></div></section>
<section id="florals" className="split dark"><div className="copy"><p className="eyebrow">HOME TO LEIA FLORALS</p><h2>Flowers for every chapter.</h2><p>From everyday bouquets to special occasions, Leia Florals brings a little more beauty to life at FIA.</p><button className="light-btn" onClick={()=>alert('Floral enquiries are coming soon. Call FIA on 07510 007001.')}>Explore Leia Florals</button></div><div className="image floral-large"></div></section>
<section id="events" className="events"><p className="eyebrow">EVENTS & PRIVATE HIRE</p><h2>Your occasion.<br/>Our space.</h2><p>For celebrations and gatherings, enquire about hosting your next moment at FIA.</p><button className="primary" onClick={()=>alert('For private hire enquiries, please call 07510 007001.')}>Enquire Now</button></section>
<section id="gallery" className="gallery"><div className="section-head"><p className="eyebrow">MOMENTS AT FIA</p><h2>Coffee. Brunch. Florals. People.</h2></div><div className="gallery-grid">{['coffee','brunch','floral','interior','coffee2','floral2','brunch2','interior2'].map((c,i)=><div className={'g '+c} key={i}></div>)}</div><a className="insta" href="https://www.instagram.com/fiacoffeehouse/" target="_blank" rel="noreferrer"><Instagram size={18}/> Follow on Instagram</a></section>
<section id="about" className="about"><div><p className="eyebrow">OUR STORY</p><h2>A space for good food, great company and beautiful things.</h2><p>FIA Coffeehouse brings together a simple idea — bring together the rituals of coffee, seasonal brunch and beautiful florals in one welcoming place.</p><p>We’re more than a café; we’re a community and a place to slow down, connect and enjoy the little things.</p></div><div className="about-image"></div></section>
<section id="visit-us" className="visit"><div><p className="eyebrow">VISIT US</p><h2>Find us in the heart of Preston.</h2><p><MapPin size={17}/>17 Birley St, Miller Arcade, Preston PR1 2QY</p><p><Phone size={17}/>07510 007001</p><p>Open · Closes 9:30 pm</p><div className="actions"><a className="primary" href="https://www.google.com/maps/search/?api=1&query=17%20Birley%20St%2C%20Miller%20Arcade%2C%20Preston%20PR1%202QY" target="_blank" rel="noreferrer">Get Directions</a><button className="outline" onClick={()=>setBooking(true)}>Book a Table</button></div></div><div className="map"><iframe title="FIA Coffeehouse map" src="https://www.google.com/maps?q=17%20Birley%20St%2C%20Miller%20Arcade%2C%20Preston%20PR1%202QY&output=embed" loading="lazy"></iframe></div></section>
<section className="newsletter"><Flower2/><div><p className="eyebrow">JOIN OUR FAMILY</p><h2>Seasonal menus, floral collections and FIA moments.</h2><form onSubmit={submitNewsletter}><input required type="email" placeholder="Your email address"/><button className="primary">Subscribe</button></form>{newsletter&&<p className="success">{newsletter}</p>}</div></section>
<footer><div className="footer-brand"><div className="logo">FIA<span>COFFEEHOUSE</span></div><small>Good Food. Brighter Days.</small></div><div className="footer-links">{['Home','Menu','Florals','Events','Gallery','About','Visit Us'].map(i=><a key={i} href={'#'+i.toLowerCase().replaceAll(' ','-')}>{i}</a>)}</div><div className="social"><a href="https://www.instagram.com/fiacoffeehouse/" target="_blank" rel="noreferrer"><Instagram/></a></div><small>© 2026 FIA Coffeehouse. All rights reserved.</small></footer>
{booking&&<div className="modal" onClick={()=>setBooking(false)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setBooking(false)}><X/></button><p className="eyebrow">BOOK A TABLE</p><h2>Good food deserves great company.</h2><form onSubmit={e=>{e.preventDefault();setBooking(false);alert('Thanks. Your booking request has been recorded for FIA Coffeehouse.')}}><input required placeholder="Name"/><input required type="email" placeholder="Email"/><input required placeholder="Phone"/><div className="two"><input required type="date"/><input required type="time"/></div><input required min="1" max="20" type="number" placeholder="Guests"/><textarea placeholder="Special requests (optional)"></textarea><button className="primary">Send Booking Request</button></form></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);