import React, { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Check, Gift, MapPin, Menu as MenuIcon, Phone, ShoppingBag, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const coffeeGroups=[
{title:'Matcha',items:[['White Chocolate Matcha','4.5'],['Raspberry & White Chocolate Matcha','4.8'],['Rosemo & White Chocolate Matcha','4.8'],['Mango Matcha','4.6'],['Vanilla Collagen Matcha','4.6']]},
{title:'Iced Coffee',items:[['Iced Pistachio & White Chocolate Latte','4.8'],['Iced Spanish Latte','4.5']]},
{title:'Juices & Soft Drinks',items:[['Orange Juice','3.5'],['Cola','2.5'],['Still Water','2.0']]},
{title:'Hot Drinks',items:[['Classic Hot','4.0'],['Strawberry & Lime','4.0'],['Pomegranate & Red Bull Fusion','4.5']]},
{title:'Hot Drinks (FIA)',items:[['Psh Chai','4.2'],['Dabterchd','4.2'],['Lotus Hot Chocolate','4.3'],['Hazelnut Chai','4.2'],['Americano','3.4'],['Cappuccino','3.4'],['Latte','3.4'],['English Tea','3.2'],['Lemon Tea','2.8']]},
{title:'Add Ons',items:[['Extra Espresso Shot','0.8'],['Oat Milk','0.8'],['Vanilla Caramel','0.8'],['Hazelnut Syrup','0.8'],['Extra Whip','0.8']]},
{title:'Bakery',items:[['Cheesecake Choc Cookie','4.5'],['Pistachio & White Chocolate Cookie','4.5'],['Pistachio & Blackberry Cookie','4.5'],['Peach & Croissant','4.6'],['Raspberry Croissant','4.6']]}
];
const brunchGroups=[
{title:'Signature Pocket Toast',items:[['Honey Roast Pocket','9.5'],['Spicy Chicken Samba','9.5'],['Avocado Veg Taco','9.5']]},
{title:'Baguettes',items:[['Fried Chicken Baguette','8.5'],['Chicken Caesar Baguette','8.5']]},
{title:'Pasta',items:[['Creamy Garlic Prawn & Steak','14.5'],['Crispy Chicken Alfredo','13.5'],['Chicken Caesar Pasta Salad','12.5']]},
{title:'Fries',items:[['Truffle Skinny Fries','5.5'],['Harissa Chicken Fries','5.5']]},
{title:'French Toasts',items:[['Kunafa French Toast','9.5'],['Mixed Berry French Toast','9.5']]}
];
const seasonal=[
{title:'Seasonal Drinks',text:'New flavours to fall for.',image:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=88'},
{title:'New Brunch Creations',text:'Fresh on the menu.',image:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1200&q=88'},
{title:'Special Moments',text:'Good food. Great company.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=88'}
];
const gallery=[
['coffee','Coffee','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=90'],['food','Food','https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1000&q=90'],['interior','Interior','https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1000&q=90'],['coffee2','Coffee','https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=90'],['food2','Food','https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=90'],['interior2','Interior','https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1000&q=90'],['coffee3','Coffee','https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=90'],['food3','Food','https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1000&q=90']
];
const nav=['Home','Menu','Gallery','About','Visit Us','Online Order'];
const slug=v=>v.toLowerCase().replaceAll(' ','-');
function InstagramIcon({size=18}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" strokeWidth="1.7"/><circle cx="12" cy="12" r="4.1" stroke="currentColor" strokeWidth="1.7"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor"/></svg>}
function Header({page,open,setOpen}){const go=p=>{setOpen(false);window.location.hash=slug(p)};return <header className={`site-header ${page==='Home'?'on-dark':''}`}><button className="brand" onClick={()=>go('Home')}><span>FIA</span><small>COFFEEHOUSE</small></button><button className="mobile-toggle" onClick={()=>setOpen(v=>!v)} aria-label="Toggle navigation">{open?<X/>:<MenuIcon/>}</button><nav className={open?'main-nav open':'main-nav'}>{nav.map(p=><button key={p} className={page===p?'current':''} onClick={()=>go(p)}>{p}</button>)}<button className="nav-cta" onClick={()=>go('Book a Table')}>Book a Table</button></nav></header>}
function Footer({go}){return <footer><div className="footer-brand"><span>FIA</span><small>COFFEEHOUSE</small></div><nav>{nav.map(p=><button key={p} onClick={()=>go(p)}>{p}</button>)}</nav><div className="footer-social"><a href="https://www.instagram.com/fiacoffeehouse/" target="_blank" rel="noreferrer"><InstagramIcon/></a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer">f</a><a href="https://www.tiktok.com/" target="_blank" rel="noreferrer">♪</a></div><div className="footer-note"><strong>Good Food. Brighter Days.</strong><small>© 2026 FIA Coffeehouse. All rights reserved.</small></div></footer>}
function Shell({page,children,go,open,setOpen}){return <div className="site"><Header page={page} open={open} setOpen={setOpen}/>{children}<Footer go={go}/></div>}
function Home({go}){return <main><section className="hero"><div className="hero-inner"><p className="eyebrow">COFFEEHOUSE · BRUNCH · GOOD FOOD</p><h1>Good Coffee.<br/>Brighter Days.</h1><p className="hero-copy">Speciality coffee, seasonal brunch and great food — all under one roof in the heart of Preston.</p><div className="button-row"><button className="cream-btn" onClick={()=>go('Menu')}>View Menu</button><button className="ghost-btn" onClick={()=>go('Online Order')}>Order Online</button></div></div><div className="scroll-mark"><i/> Scroll</div></section><section className="intro"><p className="eyebrow">THE FIA EXPERIENCE</p><h2>A space for coffee,<br/>conversation and creativity.</h2><p className="intro-copy">At FIA, speciality coffee meets seasonal brunch in a warm, considered space made for slow mornings, good conversations and brighter days.</p><div className="intro-cards"><article><div className="intro-image coffee"/><span>Speciality Coffee</span><small>Carefully sourced</small></article><article><div className="intro-image brunch"/><span>Seasonal Brunch</span><small>Fresh & creative</small></article></div></section><section className="home-feature"><div className="feature-copy"><p className="eyebrow">FIA BRUNCH</p><h2>Good food.<br/>Better company.</h2><p>Fresh, generous dishes designed for slow mornings, catch-ups and long lunches.</p><button className="dark-btn" onClick={()=>go('Menu')}>Explore the Menu <ArrowRight size={14}/></button></div><div className="feature-photo"/></section><section className="order-teaser"><div className="order-copy"><p className="eyebrow">ONLINE ORDER</p><h2>Your favourites,<br/>ready when you are.</h2><p>Order great coffee and food for collection at FIA — quick, simple and made fresh.</p><button className="dark-btn" onClick={()=>go('Online Order')}>Start an Order <ArrowRight size={14}/></button></div><div className="order-photo"/></section><section className="home-seasonal"><div className="section-title"><div><p className="eyebrow">WHAT'S HAPPENING AT FIA</p><h2>Seasonal moments.</h2></div><button className="text-link" onClick={()=>go('Seasonal')}>Explore all <ArrowRight size={14}/></button></div><div className="seasonal-strip">{seasonal.map(s=><article key={s.title}><img src={s.image} alt=""/><div><p className="eyebrow">FIA SEASONAL</p><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</div></section></main>}
function PageHero({eyebrow,title,image}){return <section className={`page-hero ${image}`}><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>Thoughtfully crafted. Beautifully served.</p></div></section>}
function MenuGroup({group,dark=false}){return <article className={`menu-group ${dark?'dark':''}`}><h3>{group.title}</h3>{group.items.map(([name,price])=><div className="menu-row" key={name}><span>{name}</span><b>{price}</b></div>)}</article>}
function MenuPage(){const [filter,setFilter]=useState('All');const filters=['All','Coffee','Brunch','Food','Bakery','Drinks'];const groups=useMemo(()=>filter==='All'?coffeeGroups:filter==='Coffee'?coffeeGroups.filter(g=>['Matcha','Iced Coffee','Hot Drinks','Hot Drinks (FIA)','Add Ons'].includes(g.title)):filter==='Bakery'?coffeeGroups.filter(g=>g.title==='Bakery'):filter==='Drinks'?coffeeGroups.filter(g=>['Juices & Soft Drinks','Hot Drinks','Iced Coffee','Hot Drinks (FIA)'].includes(g.title)):brunchGroups,[filter]);return <main className="inner"><PageHero eyebrow="OUR MENU" title="Our Menu" image="menu-hero"/><section className="menu-page"><div className="menu-tabs">{filters.map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="menu-columns">{groups.map(g=><MenuGroup group={g} key={g.title}/>)}</div><section className="brunch-panel"><div className="brunch-heading"><p className="eyebrow">FIA BRUNCH</p><h2>Good food.<br/>Brighter days.</h2></div><div className="brunch-columns">{brunchGroups.map(g=><MenuGroup group={g} dark key={g.title}/>)}</div></section></section></main>}
function OrderPage({go}){const [sent,setSent]=useState(false);return <main className="inner"><section className="order-page"><div className="order-copy"><p className="eyebrow">ONLINE ORDER</p><h1>Order Your<br/>Favourites<br/>Online.</h1><p>Great coffee and food, ready when you are. Click, order and collect at FIA.</p><div className="button-row"><button className="dark-btn" onClick={()=>document.getElementById('order-form').scrollIntoView({behavior:'smooth'})}>Start Order <ShoppingBag size={14}/></button><button className="outline-btn" onClick={()=>go('Menu')}>View Menu</button></div><div className="order-points"><span><Check/> Freshly Prepared</span><span><Check/> Easy Ordering</span><span><Check/> Click & Collect</span><span><Check/> Great Coffee</span><span><Check/> Brighter Days</span></div></div><div className="order-visual"><div className="bag">FIA<small>COFFEEHOUSE</small></div><div className="cup">FIA<small>COFFEEHOUSE</small></div><div className="croissant"/></div></section><section className="order-form-wrap" id="order-form"><div><p className="eyebrow">COLLECTION</p><h2>Build your order.</h2><p>Select a collection time and tell us what you would like. This front-end order request is ready to connect to FIA's chosen ordering platform.</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-two"><input required placeholder="Name"/><input required type="tel" placeholder="Phone"/></div><input required placeholder="Order details (e.g. 2 lattes, 1 brunch)"/><div className="form-two"><input required type="date"/><input required type="time"/></div><textarea placeholder="Notes (Optional)"/><button className="dark-btn">{sent?'Order Request Sent':'Place Order Request'} <ArrowRight size={14}/></button>{sent&&<p className="form-success">Thanks — your order request has been recorded.</p>}</form></section></main>}
function BookingPage(){const [sent,setSent]=useState(false);return <main className="inner"><section className="booking-page"><div className="booking-copy"><p className="eyebrow">RESERVATIONS</p><h1>Good Food<br/>Deserves<br/>Great Company.</h1><p>Join us at FIA for coffee, brunch or simply a moment to yourself.</p><div className="booking-photo"/></div><form className="booking-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><p className="eyebrow">BOOK A TABLE</p><h2>Book a Table</h2><input required placeholder="Name"/><input required type="email" placeholder="Email"/><input required type="tel" placeholder="Phone"/><div className="form-two"><input required type="date"/><input required type="time"/></div><input required type="number" min="1" max="20" placeholder="Guests"/><textarea placeholder="Special Requests (Optional)"/><button className="dark-btn">{sent?'Request Received':'Book Now'} <ArrowRight size={14}/></button>{sent&&<p className="form-success">Thank you. FIA will confirm availability with you.</p>}</form></section></main>}
function GalleryPage(){const [filter,setFilter]=useState('All');const filters=['All','Food','Coffee','Interior','Community'];const visible=filter==='All'?gallery:gallery.filter(g=>filter==='Community'?true:g[1]===filter);return <main className="inner"><PageHero eyebrow="MOMENTS AT FIA" title="Moments at FIA" image="gallery-hero"/><section className="gallery-page"><div className="gallery-filter">{filters.map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="gallery-mosaic">{visible.map(([key,label,url])=><div className="gallery-image" key={key} style={{backgroundImage:`url(${url})`}}><span>{label}</span></div>)}</div><a className="instagram-link" href="https://www.instagram.com/fiacoffeehouse/" target="_blank" rel="noreferrer"><InstagramIcon/> Follow us on Instagram</a></section></main>}
function AboutPage({go}){return <main className="inner"><section className="about-page"><div className="about-copy"><p className="eyebrow">OUR STORY</p><h1>A space for<br/>good food,<br/>great company.</h1><p>FIA Coffeehouse was created with a simple idea — to bring together exceptional coffee, seasonal brunch and a welcoming space in the heart of Preston.</p><p>We're more than a café; we're a community, a place to slow down, connect and enjoy the little things.</p><button className="dark-btn" onClick={()=>go('Visit Us')}>Find FIA <ArrowRight size={14}/></button></div><div className="about-photo"/></section><section className="values"><div><span>01</span><h3>Speciality Coffee</h3><p>Carefully sourced.</p></div><div><span>02</span><h3>Seasonal Brunch</h3><p>Fresh & creative.</p></div><div><span>03</span><h3>Our Community</h3><p>Always welcome.</p></div></section></main>}
function SeasonalPage(){return <main className="inner"><section className="seasonal-page"><div className="seasonal-heading"><p className="eyebrow">WHAT'S HAPPENING AT FIA</p><h1>What's Happening<br/>at FIA</h1><p>Seasonal flavours. New dishes. Special moments.</p></div><div className="seasonal-grid-page">{seasonal.map(s=><article key={s.title}><img src={s.image} alt=""/><div><p className="eyebrow">FIA SEASONAL</p><h2>{s.title}</h2><p>{s.text}</p></div></article>)}</div><button className="dark-btn seasonal-cta">View What's On</button></section></main>}
function GiftPage(){return <main className="inner"><section className="gift-page"><div className="gift-copy"><p className="eyebrow">GIVE FIA</p><h1>Give FIA</h1><p>The perfect gift for coffee lovers, brunch dates and beautiful moments.</p><button className="dark-btn" onClick={()=>window.location.href='mailto:thepixelmuses@gmail.com?subject=FIA%20Gift%20Card%20Enquiry'}>Buy a Gift Card <Gift size={15}/></button><button className="outline-btn">Learn More</button></div><div className="gift-visual"><div className="gift-card">FIA<small>COFFEEHOUSE</small></div></div></section></main>}
function VisitPage(){return <main className="inner"><section className="visit-page"><div className="visit-copy"><p className="eyebrow">VISIT US</p><h1>Find us in the<br/>heart of Preston.</h1><div className="contact-line"><MapPin/><span>17 Birley St, Miller Arcade,<br/>Preston PR1 2QY</span></div><div className="contact-line"><Phone/><a href="tel:07510007001">07510 007001</a></div><div className="contact-line"><CalendarDays/><span>Open · Closes 9:30 pm</span></div><div className="button-row"><a className="dark-btn" href="https://www.google.com/maps/search/?api=1&query=17%20Birley%20St%2C%20Miller%20Arcade%2C%20Preston%20PR1%202QY" target="_blank" rel="noreferrer">Get Directions <ArrowRight size={14}/></a><a className="outline-btn" href="https://www.google.com/maps/search/?api=1&query=17%20Birley%20St%2C%20Miller%20Arcade%2C%20Preston%20PR1%202QY" target="_blank" rel="noreferrer">View on Google Maps</a></div></div><div className="visit-map"><iframe title="FIA Coffeehouse location" src="https://www.google.com/maps?q=17%20Birley%20St%2C%20Miller%20Arcade%2C%20Preston%20PR1%202QY&output=embed" loading="lazy"/></div></section></main>}
function App(){const [open,setOpen]=useState(false);const resolve=()=>{const h=window.location.hash.slice(1);const map={'book-a-table':'Book a Table','online-order':'Online Order','visit-us':'Visit Us','gift-cards':'Gift Cards','seasonal':'Seasonal'};return map[h]||(['Home','Menu','Gallery','About'].includes(h)?h:'Home')};const [page,setPage]=useState(resolve());const go=p=>{window.location.hash=slug(p);setPage(p);setOpen(false);window.scrollTo({top:0,behavior:'smooth'})};React.useEffect(()=>{const f=()=>setPage(resolve());window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f)},[]);let content=page==='Home'?<Home go={go}/>:page==='Menu'?<MenuPage/>:page==='Online Order'?<OrderPage go={go}/>:page==='Book a Table'?<BookingPage/>:page==='Gallery'?<GalleryPage/>:page==='About'?<AboutPage go={go}/>:page==='Seasonal'?<SeasonalPage/>:page==='Gift Cards'?<GiftPage/>:<VisitPage/>;return <Shell page={page} go={go} open={open} setOpen={setOpen}>{content}</Shell>}
createRoot(document.getElementById('root')).render(<App/>);
